//create a sample post to localhost:2341
//'http://localhost:5007/ModelType/PostEither
@baseUrl = http://localhost:5007/api


///POST  :ADD QUERY MODELTYPE
###
POST {{baseUrl}}/ModelType
Content-Type: application/json

{
  "modeltypeId": "ML-0011",
  "modeltypeName": "ULTRA SIMPLE MODEL"
}


###
//GET SINGLE  MODELTYPE QUERY 

GET {{baseUrl}}/ModelType
Content-Type: application/json

{
  "modelTypeId": "ML-0011"
}




###
///GET ALL  MODELTYPE QUERY 
GET {{baseUrl}}/ModelType/GetAllAsync


###
// delete a modeltype

DELETE {{baseUrl}}/ModelType
Content-Type: application/json

{
  "modelTypeId": "ML-0011"
}
###
PUT {{baseUrl}}/ModelType
Content-Type: application/json

{
  "modeltypeId": "ML-0011",
  "modeltypeName": "MODIFIED ML2"
}
###
//END OF MODEL TYPE 
###
POST http://localhost:5007/DocumentType
Content-Type: application/json

{
  "modelTypeName": "stringxxx"
}

###
POST http://localhost:5007/DocumentType
Content-Type: application/json

{
  "documentTypeName": "stringxxx"
}

###

POST http://localhost:5007/HigherModel/PostHigherModel
Content-Type: application/json

{
  "higherModelName": "string1",
  "higherModelDescription": "string1",
  "productId": "string1",
  "capacity": 20
}



###

###

GET https://localhost:7210/WeatherForecast?productId=12345
