//create a sample post to localhost:2341
//'http://localhost:5007/ModelType/PostEither
@baseUrl = http://localhost:5007/api


///POST  :CREATE QUERY MODELTYPE
###
POST {{baseUrl}}/ModelType
Content-Type: application/json

{
  "modelTypeName": "NEW AEhddi1gghu111"
}


###
//GET SINGLE  MODELTYPE QUERY 

GET {{baseUrl}}/ModelType/ML-0011
###
//GET SINGLE  MODELTYPE QUERY 
GET {{baseUrl}}/ModelType/FIRSTMODELTYPE

###
//GET SINGLE  MODELTYPE QUERY 
GET {{baseUrl}}/ModelType/58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b

###
//GET SINGLE  MODELTYPE QUERY 

GET {{baseUrl}}/ModelType/JsonBody
Content-Type: application/json

{
  "modelTypeName": "FIRSTMODELTYPE"
}




###
///GET ALL  MODELTYPE QUERY 
GET http://localhost:5007/api/ModelType

###
///GET ALL  MODELTYPE QUERY 
GET http://localhost:5007/api/ModelType1


###
// delete a modeltype

DELETE {{baseUrl}}/ModelType/3c69923e-a68e-4348-b06c-7007f527355d
###
PUT {{baseUrl}}/ModelType
Content-Type: application/json

{
  "modelTypesId": "THIRDmodelTypesId",
  "modelTypesName": "MODIFIED ML2"
}
###
//END OF MODEL TYPE 
###
// START OF MODEL
GET {{baseUrl}}/Model/GetAllAsync
###
//GET SINGLE  MODELTYPE QUERY 

GET {{baseUrl}}/Model
Content-Type: application/json

{
  "modelId": "FIRSTMODELID22"
}



///POST  :CREATE QUERY MODEL
###
POST {{baseUrl}}/Model
Content-Type: application/json

{
   "modelId": "FIRSTMODELID14",
    "modelTypesId": "FIRSTmodelTypesId",
    "modelName": "FIRSTMODELNAME14"
}

###
// delete a modeltype

DELETE {{baseUrl}}/Model
Content-Type: application/json

{
  "modelId": "FIRSTMODELID14"
}
###
PUT {{baseUrl}}/Model
Content-Type: application/json

{
  "modelId": "SECONDMODELID1",
    "modelTypesId": "SECONDmodelTypesId",
    "modelName": "WHAT A FUCK"
}




###

###
//START OF DOCUMENT TYPE
POST http://localhost:5007/DocumentType
Content-Type: application/json

{
  "modelTypesName": "stringxxx"
}

###
POST http://localhost:5007/DocumentType
Content-Type: application/json

{
  "documentTypeName": "stringxxx"
}

###

POST http://localhost:5007/HigherModel/PostHigherModel
Content-Type: application/json

{
  "higherModelName": "string1",
  "higherModelDescription": "string1",
  "productId": "string1",
  "capacity": 20
}



###

###

GET https://localhost:7210/WeatherForecast?productId=12345
