// <auto-generated />
using System;
using DocumentVersionManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentVersionManager.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentVersionManagerContext))]
    [Migration("20231031223006_SEC")]
    partial class SEC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.CapacitySpecification", b =>
                {
                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("int");

                    b.Property<bool>("Alloy")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("AustenitizationHardnessHigh")
                        .HasColumnType("int");

                    b.Property<int?>("AustenitizationHardnessLow")
                        .HasColumnType("int");

                    b.Property<double?>("AustenitizationTemperatureInF")
                        .HasColumnType("double");

                    b.Property<int?>("AustenitizationTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("CCNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CapacitySpecificationGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DefaultCableLength")
                        .HasColumnType("int");

                    b.Property<bool>("HasScrews")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MinimumDeadLoad")
                        .HasColumnType("int");

                    b.Property<string>("NTEPCertificationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NTEPCertificationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("NominalOutput")
                        .HasColumnType("double");

                    b.Property<decimal?>("NominalOutputPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonlinearityPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NumberInBasket")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfGauges")
                        .HasColumnType("int");

                    b.Property<string>("OIMLCertificationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OIMLCertificationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Resistance")
                        .HasColumnType("int");

                    b.Property<int?>("SafeLoad")
                        .HasColumnType("int");

                    b.Property<string>("ShellMaterialName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TempRangeHigh")
                        .HasColumnType("int");

                    b.Property<int?>("TempRangeLow")
                        .HasColumnType("int");

                    b.Property<int?>("TemperingHardnessHigh")
                        .HasColumnType("int");

                    b.Property<int?>("TemperingHardnessLow")
                        .HasColumnType("int");

                    b.Property<double?>("TemperingTemperatureInF")
                        .HasColumnType("double");

                    b.Property<int?>("TemperingTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UltimateLoad")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("nMax")
                        .HasColumnType("int");

                    b.Property<double?>("vMin")
                        .HasColumnType("double");

                    b.HasKey("Capacity", "ModelName", "ModelVersionId");

                    b.HasIndex("ModelName", "ModelVersionId");

                    b.ToTable("CapacitySpecification");

                    b.HasData(
                        new
                        {
                            Capacity = 100,
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            Alloy = true,
                            Application = "APPLICATION",
                            AustenitizationHardnessHigh = 1,
                            AustenitizationHardnessLow = 1,
                            AustenitizationTemperatureInF = 1.0,
                            AustenitizationTimeInSeconds = 1,
                            CCNumber = "CCNUMBER",
                            CapacitySpecificationGuid = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b"),
                            Class = "CLASS",
                            DefaultCableLength = 20,
                            HasScrews = true,
                            MinimumDeadLoad = 1,
                            NTEPCertificationId = "NTEPCERTIFICATIONID",
                            NTEPCertificationTimestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9295),
                            NominalOutput = 1.0,
                            NominalOutputPercentage = 1m,
                            NonlinearityPercentage = 1m,
                            NumberInBasket = 1,
                            NumberOfGauges = 1,
                            OIMLCertificationId = "OIMLCERTIFICATIONID1",
                            OIMLCertificationTimestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9303),
                            Resistance = 1,
                            SafeLoad = 1,
                            ShellMaterialName = "SHELLMATERIAL1",
                            TempRangeHigh = 1,
                            TempRangeLow = 1,
                            TemperingHardnessHigh = 1,
                            TemperingHardnessLow = 1,
                            TemperingTemperatureInF = 1.0,
                            TemperingTimeInSeconds = 1,
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9286),
                            UltimateLoad = 1,
                            Username = "OLADEJI",
                            nMax = 1,
                            vMin = 1.0
                        },
                        new
                        {
                            Capacity = 100,
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 2,
                            Alloy = true,
                            Application = "APPLICATION",
                            AustenitizationHardnessHigh = 1,
                            AustenitizationHardnessLow = 1,
                            AustenitizationTemperatureInF = 1.0,
                            AustenitizationTimeInSeconds = 1,
                            CCNumber = "CCNUMBER",
                            CapacitySpecificationGuid = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b"),
                            Class = "CLASS",
                            DefaultCableLength = 20,
                            HasScrews = true,
                            MinimumDeadLoad = 1,
                            NTEPCertificationId = "NTEPCERTIFICATIONID",
                            NTEPCertificationTimestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9328),
                            NominalOutput = 1.0,
                            NominalOutputPercentage = 1m,
                            NonlinearityPercentage = 1m,
                            NumberInBasket = 1,
                            NumberOfGauges = 1,
                            OIMLCertificationId = "OIMLCERTIFICATIONID2",
                            OIMLCertificationTimestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9328),
                            Resistance = 1,
                            SafeLoad = 1,
                            ShellMaterialName = "SHELLMATERIAL2",
                            TempRangeHigh = 1,
                            TempRangeLow = 1,
                            TemperingHardnessHigh = 1,
                            TemperingHardnessLow = 1,
                            TemperingTemperatureInF = 1.0,
                            TemperingTimeInSeconds = 1,
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9324),
                            UltimateLoad = 1,
                            Username = "OLADEJI",
                            nMax = 1,
                            vMin = 1.0
                        },
                        new
                        {
                            Capacity = 100,
                            ModelName = "SECONDMODELNAME",
                            ModelVersionId = 1,
                            Alloy = true,
                            Application = "APPLICATION",
                            AustenitizationHardnessHigh = 1,
                            AustenitizationHardnessLow = 1,
                            AustenitizationTemperatureInF = 1.0,
                            AustenitizationTimeInSeconds = 1,
                            CCNumber = "CCNUMBER",
                            CapacitySpecificationGuid = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b"),
                            Class = "CLASS",
                            DefaultCableLength = 20,
                            HasScrews = true,
                            MinimumDeadLoad = 1,
                            NTEPCertificationId = "NTEPCERTIFICATIONID",
                            NTEPCertificationTimestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9335),
                            NominalOutput = 1.0,
                            NominalOutputPercentage = 1m,
                            NonlinearityPercentage = 1m,
                            NumberInBasket = 1,
                            NumberOfGauges = 1,
                            OIMLCertificationId = "OIMLCERTIFICATIONID3",
                            OIMLCertificationTimestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9335),
                            Resistance = 1,
                            SafeLoad = 1,
                            ShellMaterialName = "SHELLMATERIAL3",
                            TempRangeHigh = 1,
                            TempRangeLow = 1,
                            TemperingHardnessHigh = 1,
                            TemperingHardnessLow = 1,
                            TemperingTemperatureInF = 1.0,
                            TemperingTimeInSeconds = 1,
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 770, DateTimeKind.Utc).AddTicks(9332),
                            UltimateLoad = 1,
                            Username = "OLADEJI",
                            nMax = 1,
                            vMin = 1.0
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.CapacityTestPoint", b =>
                {
                    b.Property<int>("ModelVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CapacityTestPointGuid")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ModelVersionId", "ModelName", "TestId");

                    b.HasIndex("Capacity", "ModelName", "ModelVersionId");

                    b.ToTable("CapacityTestPoint");

                    b.HasData(
                        new
                        {
                            ModelVersionId = 1,
                            ModelName = "FIRSTMODELNAME",
                            TestId = 0,
                            Capacity = 100,
                            CapacityTestPointGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            Weight = 1
                        },
                        new
                        {
                            ModelVersionId = 2,
                            ModelName = "FIRSTMODELNAME",
                            TestId = 0,
                            Capacity = 100,
                            CapacityTestPointGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            Weight = 1
                        },
                        new
                        {
                            ModelVersionId = 1,
                            ModelName = "SECONDMODELNAME",
                            TestId = 0,
                            Capacity = 100,
                            CapacityTestPointGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            Weight = 1
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Document", b =>
                {
                    b.Property<string>("DocumentName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeOrderPDFPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentPDFPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("DocumentGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentName", "ModelName", "ModelVersionId");

                    b.HasIndex("ModelName", "ModelVersionId");

                    b.ToTable("Document");

                    b.HasData(
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            ChangeOrderPDFPath = "CHANGE ORDER PATH",
                            ContentPDFPath = "CONTENT PDF PATH",
                            DocumentDescription = "SIMPLE DESCRITION OF DOCUMENT",
                            DocumentGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 773, DateTimeKind.Utc).AddTicks(1503)
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc A",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            ChangeOrderPDFPath = "CHANGE ORDER PATH",
                            ContentPDFPath = "CONTENT PDF PATH",
                            DocumentDescription = "SIMPLE DESCRITION OF DOCUMENT",
                            DocumentGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 773, DateTimeKind.Utc).AddTicks(1526)
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc B",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            ChangeOrderPDFPath = "CHANGE ORDER PATH",
                            ContentPDFPath = "CONTENT PDF PATH",
                            DocumentDescription = "SIMPLE DESCRITION OF DOCUMENT",
                            DocumentGuid = new Guid("7808711f-544a-423d-8d99-f00c31e35be5"),
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 773, DateTimeKind.Utc).AddTicks(1531)
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver2 DOc A",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 2,
                            ChangeOrderPDFPath = "CHANGE ORDER PATH",
                            ContentPDFPath = "CONTENT PDF PATH",
                            DocumentDescription = "SIMPLE DESCRITION OF DOCUMENT",
                            DocumentGuid = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b"),
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 773, DateTimeKind.Utc).AddTicks(1534)
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.DocumentDocumentType", b =>
                {
                    b.Property<string>("DocumentName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentTypeName")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("DocumentDocumentTypeGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("DocumentName", "ModelName", "ModelVersionId", "DocumentTypeName");

                    b.ToTable("DocumentDocumentType");

                    b.HasData(
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc A",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            DocumentTypeName = "Cabling",
                            DocumentDocumentTypeGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc A",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            DocumentTypeName = "Chroming",
                            DocumentDocumentTypeGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc A",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            DocumentTypeName = "Sealing",
                            DocumentDocumentTypeGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc B",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            DocumentTypeName = "Cabling",
                            DocumentDocumentTypeGuid = new Guid("7808711f-544a-423d-8d99-f00c31e35be5")
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc B",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            DocumentTypeName = "Chroming",
                            DocumentDocumentTypeGuid = new Guid("7808711f-544a-423d-8d99-f00c31e35be5")
                        },
                        new
                        {
                            DocumentName = "FIRSTMODELNAME ver1 DOc B",
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            DocumentTypeName = "Sealing",
                            DocumentDocumentTypeGuid = new Guid("7808711f-544a-423d-8d99-f00c31e35be5")
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.DocumentType", b =>
                {
                    b.Property<string>("TypeName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("DocumentTypeGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("TypeName");

                    b.ToTable("DocumentType");

                    b.HasData(
                        new
                        {
                            TypeName = "Cabling",
                            DocumentTypeGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            TypeName = "Chroming",
                            DocumentTypeGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            TypeName = "Sealing",
                            DocumentTypeGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            TypeName = "Gauging",
                            DocumentTypeGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            TypeName = "Wiring",
                            DocumentTypeGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.HigherModel", b =>
                {
                    b.Property<string>("HigherModelName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("HigherModelDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Id")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HigherModelName");

                    b.ToTable("HigherModel");

                    b.HasData(
                        new
                        {
                            HigherModelName = "HigherModel1",
                            Capacity = 1,
                            HigherModelDescription = "HigherModel1",
                            Id = "a54b3659-697e-4732-9ab5-ec43c2c103bd",
                            ProductId = "HigherModel1"
                        },
                        new
                        {
                            HigherModelName = "HigherModel2",
                            Capacity = 12,
                            HigherModelDescription = "HigherModel12",
                            Id = "773d2b35-8572-4cae-a694-d216435fdd2b",
                            ProductId = "HigherModel12"
                        },
                        new
                        {
                            HigherModelName = "HigherModel3",
                            Capacity = 13,
                            HigherModelDescription = "HigherModel1",
                            Id = "7b4b5b41-2c52-4cf9-a39a-ed059b8d80b6",
                            ProductId = "HigherModel13"
                        },
                        new
                        {
                            HigherModelName = "HigherModel4",
                            Capacity = 14,
                            HigherModelDescription = "HigherModel14",
                            Id = "842a9f3f-2b1a-4a24-a9b8-b3e5a20c4660",
                            ProductId = "HigherModel14"
                        },
                        new
                        {
                            HigherModelName = "HigherModel5",
                            Capacity = 5,
                            HigherModelDescription = "HigherModel5",
                            Id = "cdbdc281-74ec-4428-b7b7-466a4ee985ea",
                            ProductId = "HigherModel5"
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Model", b =>
                {
                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModelTypesName")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("ModelName");

                    b.HasIndex("ModelTypesName");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            ModelName = "FIRSTMODELNAME",
                            ModelId = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            ModelTypesName = "FIRSTMODELTYPE"
                        },
                        new
                        {
                            ModelName = "SECONDMODELNAME",
                            ModelId = new Guid("7808711f-544a-423d-8d99-f00c31e35be5"),
                            ModelTypesName = "FIRSTMODELTYPE"
                        },
                        new
                        {
                            ModelName = "THIRDMODELNAME",
                            ModelId = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b"),
                            ModelTypesName = "SECONDMODELTYPE"
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelTypes", b =>
                {
                    b.Property<string>("ModelTypesName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ModelTypesId")
                        .HasColumnType("char(36)");

                    b.HasKey("ModelTypesName");

                    b.ToTable("ModelType");

                    b.HasData(
                        new
                        {
                            ModelTypesName = "FIRSTMODELTYPE",
                            ModelTypesId = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            ModelTypesName = "SECONDMODELTYPE",
                            ModelTypesId = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b")
                        },
                        new
                        {
                            ModelTypesName = "THIRDMODELTYPE",
                            ModelTypesId = new Guid("3c69923e-a68e-4348-b06c-7007f527355d")
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelVersion", b =>
                {
                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelVersionGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModelVersionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VersionDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ModelName", "ModelVersionId");

                    b.ToTable("ModelVersion");

                    b.HasData(
                        new
                        {
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 1,
                            ModelVersionGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63"),
                            ModelVersionName = "FIRST_VERSION_FIRSTMODEL_NAME",
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 777, DateTimeKind.Utc).AddTicks(870),
                            Username = "OLADEJI",
                            VersionDescription = "SPECIAL DESIGN"
                        },
                        new
                        {
                            ModelName = "FIRSTMODELNAME",
                            ModelVersionId = 2,
                            ModelVersionGuid = new Guid("7808711f-544a-423d-8d99-f00c31e35be5"),
                            ModelVersionName = "SECOND_VERSION_FIRSTMODELNAME",
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 777, DateTimeKind.Utc).AddTicks(880),
                            Username = "OLADEJI",
                            VersionDescription = "AUTO DESIGN TO COMBAT SPLIILING"
                        },
                        new
                        {
                            ModelName = "SECONDMODELNAME",
                            ModelVersionId = 1,
                            ModelVersionGuid = new Guid("58dcf5c5-5a00-4ffa-bb37-9374a8d3c69b"),
                            ModelVersionName = "FIRST_VERSION_SECONDMODELNAME",
                            Timestamp = new DateTime(2023, 10, 31, 22, 30, 6, 777, DateTimeKind.Utc).AddTicks(882),
                            Username = "OLADEJI",
                            VersionDescription = "INITIAL DESIGN"
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ShellMaterial", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Alloy")
                        .HasColumnType("int");

                    b.Property<Guid>("ShellMaterialGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Name", "Alloy");

                    b.ToTable("ShellMaterial");

                    b.HasData(
                        new
                        {
                            Name = "ShellMAterial1",
                            Alloy = 1,
                            ShellMaterialGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            Name = "ShellMAterial1",
                            Alloy = 2,
                            ShellMaterialGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            Name = "ShellMAterial2",
                            Alloy = 1,
                            ShellMaterialGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        },
                        new
                        {
                            Name = "ShellMAterial2",
                            Alloy = 2,
                            ShellMaterialGuid = new Guid("b27c2c19-522b-49d1-83bf-e80d4dde8c63")
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.CapacitySpecification", b =>
                {
                    b.HasOne("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelVersion", "ModelVersion")
                        .WithMany("CapacitySpecifications")
                        .HasForeignKey("ModelName", "ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.CapacityTestPoint", b =>
                {
                    b.HasOne("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.CapacitySpecification", "CapacitySpecification")
                        .WithMany("CapacityTestPoints")
                        .HasForeignKey("Capacity", "ModelName", "ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapacitySpecification");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Document", b =>
                {
                    b.HasOne("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelVersion", "ModelVersion")
                        .WithMany("Documents")
                        .HasForeignKey("ModelName", "ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.DocumentDocumentType", b =>
                {
                    b.HasOne("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Document", "Document")
                        .WithMany("DocumentDocumentTypes")
                        .HasForeignKey("DocumentName", "ModelName", "ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Model", b =>
                {
                    b.HasOne("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelTypes", "ModelTypes")
                        .WithMany("Models")
                        .HasForeignKey("ModelTypesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelTypes");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelVersion", b =>
                {
                    b.HasOne("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Model", "Models")
                        .WithMany("ModelVersions")
                        .HasForeignKey("ModelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Models");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.CapacitySpecification", b =>
                {
                    b.Navigation("CapacityTestPoints");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Document", b =>
                {
                    b.Navigation("DocumentDocumentTypes");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.Model", b =>
                {
                    b.Navigation("ModelVersions");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelTypes", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelVersion", b =>
                {
                    b.Navigation("CapacitySpecifications");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
