// <auto-generated />
using DocumentVersionManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentVersionManager.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentVersionManagerContext))]
    [Migration("20231012171038_doctype3")]
    partial class doctype3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.DocumentType", b =>
                {
                    b.Property<string>("TypeName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("TypeName");

                    b.ToTable("DocumentType");

                    b.HasData(
                        new
                        {
                            TypeName = "Cabling"
                        },
                        new
                        {
                            TypeName = "Chroming"
                        },
                        new
                        {
                            TypeName = "Sealing"
                        },
                        new
                        {
                            TypeName = "Gauging"
                        },
                        new
                        {
                            TypeName = "Wiring"
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.HigherModel", b =>
                {
                    b.Property<string>("HigherModelName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Id")
                        .HasColumnType("longtext");

                    b.HasKey("HigherModelName");

                    b.ToTable("HigherModel");

                    b.HasData(
                        new
                        {
                            HigherModelName = "HigherModel1",
                            Id = "a3344eec-2da3-49b4-aeb3-ac70f4973bf5"
                        },
                        new
                        {
                            HigherModelName = "HigherModel2",
                            Id = "d97a7d19-9748-4346-999a-cfb0c5d6ef7d"
                        },
                        new
                        {
                            HigherModelName = "HigherModel3",
                            Id = "e7194d47-5078-4aed-b2bd-88e338d9d665"
                        },
                        new
                        {
                            HigherModelName = "HigherModel4",
                            Id = "da7452a5-4b37-4443-9ed6-d76f1680f176"
                        },
                        new
                        {
                            HigherModelName = "HigherModel5",
                            Id = "a84c2888-2f82-4f56-b1c4-f26b82be5e51"
                        });
                });

            modelBuilder.Entity("DocumentVersionManager.Domain.ModelAggregateRoot.Entities.ModelType", b =>
                {
                    b.Property<string>("ModelTypeName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("ModelTypeName");

                    b.ToTable("ModelType");

                    b.HasData(
                        new
                        {
                            ModelTypeName = "FIRSTMODELTYPE"
                        },
                        new
                        {
                            ModelTypeName = "SECONDMODELTYPE"
                        },
                        new
                        {
                            ModelTypeName = "THIRDMODELTYPE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
